<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-06-01T18:03:43Z" name="Default suite" finished-at="2021-06-01T18:04:20Z" duration-ms="37821">
    <groups>
    </groups>
    <test started-at="2021-06-01T18:03:43Z" name="Default test" finished-at="2021-06-01T18:04:20Z" duration-ms="37821">
      <class name="tests.SajtTest">
        <test-method is-config="true" signature="createDriver()[pri:0, instance:tests.SajtTest@762ef0ea]" started-at="2021-06-01T18:03:43Z" name="createDriver" finished-at="2021-06-01T18:03:48Z" duration-ms="5939" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createDriver -->
        <test-method signature="invalidLoginTest()[pri:1, instance:tests.SajtTest@762ef0ea]" started-at="2021-06-01T18:03:49Z" name="invalidLoginTest" finished-at="2021-06-01T18:03:55Z" duration-ms="6000" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidLoginTest -->
        <test-method signature="loginTest()[pri:2, instance:tests.SajtTest@762ef0ea]" started-at="2021-06-01T18:03:55Z" name="loginTest" finished-at="2021-06-01T18:03:58Z" duration-ms="3192" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method signature="excelLogin()[pri:3, instance:tests.SajtTest@762ef0ea]" started-at="2021-06-01T18:03:58Z" name="excelLogin" finished-at="2021-06-01T18:04:08Z" duration-ms="10749" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/],
expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/],
expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at tests.SajtTest.excelLogin(SajtTest.java:123)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- excelLogin -->
        <test-method signature="cenaRastuce()[pri:4, instance:tests.SajtTest@762ef0ea]" started-at="2021-06-01T18:04:08Z" name="cenaRastuce" finished-at="2021-06-01T18:04:20Z" duration-ms="11880" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cenaRastuce -->
      </class> <!-- tests.SajtTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
